### ISSUE TITLE
If application is swipe from task manager or recent list of some phone(Lenovo, Xiaomi..) the notification is not getting

### ISSUE THREAD

**Issue by riyask** [arleyandrada/PushClient#126]
Hi,

In some phones(Lenovo, Xiami etc) the notification is not getting if the application is swipe from task manager. But there is no issues in samsung, Micromax etc. It is an important issue as far as users are concerned. How can  solve this issue?

**Comment by arleyandrada** [comment]
Duplicated Issue: https://github.com/arleyandrada/PushClient/issues/120

**Comment by riyask** [comment]
Hi Areley,
Thanks for your reply. I consulted an expert regarding this. The some phones kills normal service when swiping from task manager. To solve this issues we want write it as system service. The android won't kill the system services. Is it possible in our module.

**Comment by arleyandrada** [comment]
System service is not a solution to this problem.

The push notification service is a piece of the S.O. and the app acts as a passive part (broadcast receiver), waiting for "communication" with the S.O.

There is no way to write a "push notification client module" as a system service.

**Comment by riyask** [comment]
Hi,
Issue is still persisting. I don't have any idea how to solve it. Actually
I spent lots of time to solve this issue. My client is shouting me not
solving this simple issue. I changed phone settings and everything. It will
be more better if you can solve this issue. I trusted your piad module so I
purchased this. If you want additional payment I am ready to pay you. Give
me a proper solution

Regards
Riyas

**Comment by riyask** [comment]
Gentle Reminder!!!

**Comment by arleyandrada** [comment]
Xiaomi for security purposes disables the Notification for each Application. Follow these steps to receive messages in background once they quit the app using cleaner.
- Enable Autostart
- Enable Floating and Lock Screen Notification
- Enable AutoStart

Open Security App.
- Got to Permissions, then Click on Auto Start Management.
- Add/Enable auto start apps (e.g. Whatsapp).
- Enable Floating and Lock Screen Notification

Open Settings App.
- Click on Notifications, then click on Manage Notifications.
- Tap on the App which you are looking for (e.g. WhatsApp).
- Enable Show in notification shade / Show on lockscreen and in drop down option.

For Reference check this out : [http://support.hike.in/entries/55998480-I-m-not-getting-notification-on-my-Xiaomi-Phone-For-MIUI-6-](http://support.hike.in/entries/55998480-I-m-not-getting-notification-on-my-Xiaomi-Phone-For-MIUI-6-)

**Comment by arleyandrada** [comment]
Yes, it is a paid module, but you will not find any other push module that can solve this issue because it is not possible.

You will find some workaround to this issue in web searches, but none of them are eligible to be included in my or in any module because they are buggy, not trusted or resource wasters.

It is not a problem faced only by your app.

Again: If the user force-stops your app, they are indicating that they do not want your app to run again, for any reason, until they manually launch it again... and some Android distributions like used by Lenovo and Xiaomi chooses to force this behavior and sometimes offer some configuration options.

No, I don't want "additional payment".

Yes, build apps is not easy and we need to deal with lots of different behaviors, scenarios and limitations.

Sorry if I can't help.
