### ISSUE TITLE
Weird behaviour

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#19]
Hi,

I have purchased the PushModule yesterday.

I have noticed a weird behaviour that stops me to use this module in production release.

If the Android device receives multiple notifications, only a click on the last notification opens the app. Click on all other notifications do nothing

Can you please solve this problem?

BTW: I have also posted a question "setLargeIcon and setNumber" in the marketplace. Would be nice if you can also respond on this.

Thx

**Comment by arleyandrada** [comment]
Hi,

I'm just reading your email.

I need reproduce the reported behavior so that I have a position to propose some solution.

No one reported this problem before and I don't faced this problem in my own apps.

My first questions and tips are:

You need to register my module and call the regiterPush method at every app startup, regardless if you have registered the device before; Code it at app.js or index.js (main Alloy controller);

Are you setting / sending a notificationId (different to each message) attribute in your payload data?

If my tips don't solve your problem, maybe you can share with me a minimal version of your project with the reported problem and describe each send payload data.

I wait for your response.

Regards,

Arley

**Comment by arleyandrada** [comment]
Hi,

Related to your question about custom icons and set number (badge) for Android, maybe I can release a special version to you before my next official version, but before that I would like to ensure that the current module version is working perfectly for you.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley,

thanks for your reply.

To your questions: yes, I register the module and call the registerPush method every time on app startup. This is not the problem as I do receive push notifications.

A unique notificationId is also sent with each message.

I'm using the example app.js so no other modifications but still it doesn't work properly.

Can you please test it with your app and multiple notifications? Only the last notification triggers the app launch, all older notifications do not.

Thx

**Comment by arleyandrada** [comment]
Hi,

You are right! You found a bug in my module!

Attached is a new fixed version of my module.

In gratitude, I also released the option to set "badge" and "largeIcon" from payload data on Android notifications as suggested.

Please let me know if everything is OK now.

Thanks,

Arley

**Comment by somefakeuser** [comment]
Hi Arley,

thanks a lot! Now everything works perfect, even badge and largeIcon.

Best
