### ISSUE TITLE
Parse.com

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#53]
Hi Arley how are you ?

   It is me again :( i am trying to use the module for ios now. When i checked the parse.com i can see the devicetoken at "Core" section, when i send the notification from parse.com i can't retrieve it from the device. I have created the .p12 file and uploaded it to the parse.com and i didn't use any password at .p12 file. Is there anything which i should do ?

Thanks

**Comment by arleyandrada** [comment]
I suggest you to try some things:
- Check if the "Certificate bundle identifier" is exactly the same on "Apple Developer" (from where you get the certificates) and on TiApp.xml from your Titanium Project;
- Upload to Parse.com and try your "Development" certificate and after that try with your "Production" certificate too;
- Uninstall and reinstall your app on your devices;
- Check if your Apple device is connected to the Internet;
- After send a message from Parse.com, check the delivery report;
- Try to send a "simple message" instead of JSON message to Apple devices;
- Try to send push notifications to Apple devices with your app in foreground and check any app log or any PushClient callback;

P.S.: It's not possible to test Push Notifications on emulator.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley, 

   I was sick because of the cold and I couldn't write you, I will try and let you know but I have done most of them already. 

Thanks a lot for your help
